#include <string>

#include "gtest/gtest.h"
#include "generic_graph_tests.h"
#include "generic_set_vertex_graph_tests.h"
#include "generic_set_vertex_digraph_tests.h"
#include "../graph.h"
#include "../full_labeled_set_vertex_digraph.h"

using tested_graph = MAIN_LIBRARY_NAMESPACE::full_labeled_set_vertex_digraph<std::size_t,std::string,std::string>;

IS_A_GRAPH_TEST(full_labeled_set_vertex_digraph,tested_graph,std::size_t);

NO_VERTICES_AFTER_DEFAULT_CONSTRUCTION_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_IS_A_SET_VERTEX_GRAPH_TEST(full_labeled_set_vertex_digraph,tested_graph,std::size_t);

SET_VERTEX_GRAPH_IS_NOT_A_MULTISET_VERTEX_GRAPH_TEST(full_labeled_set_vertex_digraph,tested_graph,std::size_t);

SET_VERTEX_GRAPH_ORDER_METHOD_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CORRECT_RETURNED_BOOLEAN_AFTER_VERTEX_INSERTION_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CORRECT_VERTEX_POINTER_DEREFERENCING_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CORRECT_VERTEX_POINTER_DEREFERENCING_AFTER_OTHER_VERTICES_ERASION_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CORRECT_CONSTANT_VERTEX_POINTER_CONVERSION_TEST_1(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_VERTEX_POINTER_EQUALITY_OPERATOR_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_VERTEX_POINTER_INEQUALITY_OPERATOR_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CONSTANT_VERTEX_POINTER_EQUALITY_OPERATOR_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CONSTANT_VERTEX_POINTER_INEQUALITY_OPERATOR_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CORRECT_RETURNED_VERTEX_POINTER_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_VERTEX_POINTER_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CORRECT_RETURNED_CONSTANT_VERTEX_POINTER_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_CONSTANT_VERTEX_POINTER_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_GRAPH_UNABLE_TO_CONVERT_A_VERTEX_POINTER_TO_MULTISET_VERTEX_POINTER_TEST(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_NOT_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_NOT_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_NOT_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_NOT_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_NOT_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_NOT_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_NOT_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_NOT_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_vertex_digraph,tested_graph);