#include <string>

#include "gtest/gtest.h"
#include "graphdom_tests_utility.h"
#include "generic_graph_tests.h"
#include "generic_ugraph_tests.h"
#include "generic_set_graph_tests.h"
#include "generic_set_ugraph_tests.h"
#include "generic_labeled_vertex_graph_tests.h"
#include "generic_labeled_vertex_set_graph_tests.h"
#include "graphdom/graph.h"
#include "graphdom/full_labeled_set_ugraph.h"

using tested_graph = graphdom::full_labeled_set_ugraph<std::size_t,std::string,std::string>;
using tested_graph_2 = graphdom::full_labeled_set_ugraph<graphdom_tests::heap_value<std::size_t>,std::string,std::string>;
using tested_graph_3 = graphdom::full_labeled_set_ugraph<graphdom_tests::heap_value<std::size_t>,graphdom_tests::heap_value<std::string>,std::string>;

IS_A_GRAPH_TEST(full_labeled_set_ugraph,tested_graph,std::size_t);

UGRAPH_IS_A_NON_MIXED_GRAPH_TEST(full_labeled_set_ugraph,tested_graph,std::size_t);

UGRAPH_IS_NOT_A_MIXED_GRAPH_TEST(full_labeled_set_ugraph,tested_graph,std::size_t);

NO_VERTICES_AFTER_DEFAULT_CONSTRUCTION_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_IS_A_SET_GRAPH_TEST(full_labeled_set_ugraph,tested_graph,std::size_t);

SET_GRAPH_IS_NOT_A_MULTISET_GRAPH_TEST(full_labeled_set_ugraph,tested_graph,std::size_t);

SET_GRAPH_ORDER_METHOD_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_ORDER_METHOD_WITH_MOVE_INSERTION_WITHOUT_LABEL_TEST(full_labeled_set_ugraph,tested_graph_2);

SET_GRAPH_CORRECT_RETURNED_BOOLEAN_AFTER_VERTEX_INSERTION_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_CORRECT_RETURNED_BOOLEAN_AFTER_VERTEX_MOVE_INSERTION_WITHOUT_LABEL_TEST(full_labeled_set_ugraph,tested_graph_2);

SET_GRAPH_INVALIDATED_SOURCE_AFTER_SUCCESSFUL_VERTEX_MOVE_INSERTION_WITHOUT_LABEL_TEST(full_labeled_set_ugraph,tested_graph_2);

SET_GRAPH_NOT_INVALIDATED_SOURCE_AFTER_UNSUCCESSFUL_VERTEX_MOVE_INSERTION_WITHOUT_LABEL_TEST(full_labeled_set_ugraph,tested_graph_2);

SET_GRAPH_CORRECT_VERTEX_HANDLE_DEREFERENCING_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_CORRECT_VERTEX_HANDLE_DEREFERENCING_AFTER_OTHER_VERTICES_ERASION_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_CORRECT_VERTEX_CONST_HANDLE_CONVERSION_TEST_1(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_VERTEX_HANDLE_EQUALITY_OPERATOR_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_VERTEX_HANDLE_INEQUALITY_OPERATOR_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_VERTEX_CONST_HANDLE_EQUALITY_OPERATOR_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_VERTEX_CONST_HANDLE_INEQUALITY_OPERATOR_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_CORRECT_RETURNED_VERTEX_HANDLE_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_VERTEX_HANDLE_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_CORRECT_RETURNED_VERTEX_CONST_HANDLE_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_VERTEX_CONST_HANDLE_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_set_ugraph,tested_graph);

SET_GRAPH_UNABLE_TO_CONVERT_A_VERTEX_HANDLE_TO_MULTISET_VERTEX_HANDLE_TEST(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_INSERTION_WITHOUT_LABEL_VERTEX_HANDLE_ADJ_LIST_NOT_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_INSERTION_WITHOUT_LABEL_VERTEX_HANDLE_ADJ_LIST_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_INSERTION_WITHOUT_LABEL_VERTEX_HANDLE_CONST_ADJ_LIST_NOT_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_INSERTION_WITHOUT_LABEL_VERTEX_HANDLE_CONST_ADJ_LIST_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_INSERTION_WITHOUT_LABEL_VERTEX_CONST_HANDLE_ADJ_LIST_NOT_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_INSERTION_WITHOUT_LABEL_VERTEX_CONST_HANDLE_ADJ_LIST_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_INSERTION_WITHOUT_LABEL_VERTEX_CONST_HANDLE_CONST_ADJ_LIST_NOT_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_INSERTION_WITHOUT_LABEL_VERTEX_CONST_HANDLE_CONST_ADJ_LIST_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_ERASION_VERTEX_HANDLE_ADJ_LIST_NOT_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_ERASION_VERTEX_HANDLE_ADJ_LIST_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_ERASION_VERTEX_HANDLE_CONST_ADJ_LIST_NOT_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_ERASION_VERTEX_HANDLE_CONST_ADJ_LIST_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_ERASION_VERTEX_CONST_HANDLE_ADJ_LIST_NOT_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_ERASION_VERTEX_CONST_HANDLE_ADJ_LIST_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_ERASION_VERTEX_CONST_HANDLE_CONST_ADJ_LIST_NOT_C_METHODS(full_labeled_set_ugraph,tested_graph);

SET_UGRAPH_CORRECT_EDGES_ERASION_VERTEX_CONST_HANDLE_CONST_ADJ_LIST_C_METHODS(full_labeled_set_ugraph,tested_graph);

IS_A_LABELED_VERTEX_GRAPH(full_labeled_set_ugraph,tested_graph,std::size_t,std::string);

LABELED_VERTEX_SET_GRAPH_IS_A_LABELED_VERTEX_SET_GRAPH_TEST(full_labeled_set_ugraph,tested_graph,std::size_t,std::string);

LABELED_VERTEX_SET_GRAPH_IS_NOT_A_LABELED_VERTEX_MULTISET_GRAPH_TEST(full_labeled_set_ugraph,tested_graph,std::size_t,std::string);

LABELED_VERTEX_SET_GRAPH_CORRECT_VERTEX_INSERTION_WITH_LABEL_CORE_LVALUE_LABEL_LVALUE_VERTEX_HANDLE_TEST(full_labeled_set_ugraph,tested_graph_3);

LABELED_VERTEX_SET_GRAPH_CORRECT_VERTEX_INSERTION_WITH_LABEL_CORE_LVALUE_LABEL_RVALUE_VERTEX_HANDLE_TEST(full_labeled_set_ugraph,tested_graph_3);

LABELED_VERTEX_SET_GRAPH_CORRECT_VERTEX_INSERTION_WITH_LABEL_CORE_RVALUE_LABEL_LVALUE_VERTEX_HANDLE_TEST(full_labeled_set_ugraph,tested_graph_3);

LABELED_VERTEX_SET_GRAPH_CORRECT_VERTEX_INSERTION_WITH_LABEL_CORE_RVALUE_LABEL_RVALUE_VERTEX_HANDLE_TEST(full_labeled_set_ugraph,tested_graph_3);