#include <string>

#include "gtest/gtest.h"
#include "generic_graph_tests.h"
#include "generic_multiset_vertex_graph_tests.h"
#include "../graph.h"
#include "../full_labeled_multiset_vertex_digraph.h"

using tested_graph = MAIN_LIBRARY_NAMESPACE::full_labeled_multiset_vertex_digraph<std::size_t,std::string,std::string>;

IS_A_GRAPH_TEST(full_labeled_multiset_vertex_digraph,tested_graph,std::size_t);

NO_VERTICES_AFTER_DEFAULT_CONSTRUCTION_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_IS_A_MULTISET_VERTEX_GRAPH_TEST(full_labeled_multiset_vertex_digraph,tested_graph,std::size_t);

MULTISET_VERTEX_GRAPH_IS_NOT_A_SET_VERTEX_GRAPH_TEST(full_labeled_multiset_vertex_digraph,tested_graph,std::size_t);

MULTISET_VERTEX_GRAPH_ORDER_METHOD_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CORRECT_SPECIFIC_VERTEX_POINTER_DEREFERENCING_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CORRECT_SPECIFIC_VERTEX_POINTER_DEREFERENCING_AFTER_OTHER_VERTICES_ERASION_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CORRECT_CONVERSION_FROM_SPECIFIC_VERTEX_POINTER_TO_CONST_VERTEX_POINTER_TEST_1(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CORRECT_CONVERSION_FROM_SPECIFIC_VERTEX_POINTER_TO_GENERIC_VERTEX_POINTER_TEST_1(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CORRECT_CONVERSION_FROM_GENERIC_VERTEX_POINTER_TO_SPECIFIC_VERTEX_POINTER_TEST_1(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_SPECIFIC_VERTEX_POINTER_EQUALITY_OPERATOR_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_SPECIFIC_VERTEX_POINTER_INEQUALITY_OPERATOR_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_VERTEX_POINTER_EQUALITY_OPERATOR_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_VERTEX_POINTER_INEQUALITY_OPERATOR_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CONSTANT_VERTEX_POINTER_EQUALITY_OPERATOR_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CONSTANT_VERTEX_POINTER_INEQUALITY_OPERATOR_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CORRECT_RETURNED_SPECIFIC_VERTEX_POINTER_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_SPECIFIC_VERTEX_POINTER_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CORRECT_RETURNED_VERTEX_POINTER_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_VERTEX_POINTER_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CORRECT_RETURNED_CONSTANT_VERTEX_POINTER_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_multiset_vertex_digraph,tested_graph);

MULTISET_VERTEX_GRAPH_CONSTANT_VERTEX_POINTER_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_multiset_vertex_digraph,tested_graph);

