#include <string>

#include "gtest/gtest.h"
#include "generic_graph_tests.h"
#include "generic_digraph_tests.h"
#include "generic_set_graph_tests.h"
#include "generic_set_digraph_tests.h"
#include "graphdom/graph.h"
#include "graphdom/full_labeled_set_digraph.h"

using tested_graph = graphdom::full_labeled_set_digraph<std::size_t,std::string,std::string>;

IS_A_GRAPH_TEST(full_labeled_set_digraph,tested_graph,std::size_t);

DIGRAPH_IS_A_NON_MIXED_GRAPH_TEST(full_labeled_set_digraph,tested_graph,std::size_t);

DIGRAPH_IS_NOT_A_MIXED_GRAPH_TEST(full_labeled_set_digraph,tested_graph,std::size_t);

NO_VERTICES_AFTER_DEFAULT_CONSTRUCTION_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_IS_A_SET_GRAPH_TEST(full_labeled_set_digraph,tested_graph,std::size_t);

SET_GRAPH_IS_NOT_A_MULTISET_GRAPH_TEST(full_labeled_set_digraph,tested_graph,std::size_t);

SET_GRAPH_ORDER_METHOD_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_CORRECT_RETURNED_BOOLEAN_AFTER_VERTEX_INSERTION_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_CORRECT_VERTEX_HANDLE_DEREFERENCING_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_CORRECT_VERTEX_HANDLE_DEREFERENCING_AFTER_OTHER_VERTICES_ERASION_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_CORRECT_VERTEX_CONST_HANDLE_CONVERSION_TEST_1(full_labeled_set_digraph,tested_graph);

SET_GRAPH_VERTEX_HANDLE_EQUALITY_OPERATOR_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_VERTEX_HANDLE_INEQUALITY_OPERATOR_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_VERTEX_CONST_HANDLE_EQUALITY_OPERATOR_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_VERTEX_CONST_HANDLE_INEQUALITY_OPERATOR_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_CORRECT_RETURNED_VERTEX_HANDLE_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_VERTEX_HANDLE_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_set_digraph,tested_graph);

SET_GRAPH_CORRECT_RETURNED_VERTEX_CONST_HANDLE_REFERENCE_AFTER_ASSIGNMENT_TEST(full_labeled_set_digraph,tested_graph);

SET_GRAPH_VERTEX_CONST_HANDLE_ASSIGNMENT_OPERATOR_TEST_1(full_labeled_set_digraph,tested_graph);

SET_GRAPH_UNABLE_TO_CONVERT_A_VERTEX_HANDLE_TO_MULTISET_VERTEX_HANDLE_TEST(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_NOT_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_NOT_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_NOT_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_NOT_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_INSERTION_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_NOT_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_NOT_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_NOT_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_NOT_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_CONSTANT_VERTEX_PTR_NOT_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_NOT_C_METHODS(full_labeled_set_digraph,tested_graph);

SET_VERTEX_DIGRAPH_CORRECT_EDGES_ERASION_CONSTANT_VERTEX_PTR_CONSTANT_ADJ_LIST_C_METHODS(full_labeled_set_digraph,tested_graph);