name: Build Doxygen User Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GraphDom Repository
        uses: actions/checkout@v4

      - name: Doxygen Installation
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate user documentation
        run: |
          doxygen user_docs_doxygen_config_file

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: generated_docs/user_docs/html

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4